spring:
  application:
      name: countries-service
      #  JPA Configuration
  jpa:
      show-sql: true
  h2:
      console:
          enabled: true   
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
server:
  port: 8000 



